-- //////////////////////////////////////////////////////////////////////////////////////////////// --


-- CREATE DATABASE IF NOT EXISTS `apollo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
-- USE `apollo`;

-- CREATE TABLE IF NOT EXISTS `doadores` (
--   `id` varchar(255) UNIQUE NOT NULL,
--   `nome` varchar(120) UNIQUE NOT NULL,
--   `cpf` varchar(120),
--   `endereco` varchar(255) NOT NULL,
--   `email` varchar(100) UNIQUE NOT NULL,
--   `telefone` varchar(100) UNIQUE NOT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 14:38:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- //////////////////////////////////////////////////////////////////////////////////////////////// -- 
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apollo
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `apollo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
-- -----------------------------------------------------
-- Schema apollo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apollo` DEFAULT CHARACTER SET utf8 ;
USE `apollo` ;
-- -----------------------------------------------------
-- Table `apollo`.`doadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`doadores` (
  `id` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `apollo`.`historico_doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`historico_doacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `data` VARCHAR(255) NULL,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idhd_idx` (`nome` ASC) VISIBLE,
  CONSTRAINT `idhd`
    FOREIGN KEY (`nome`) REFERENCES `apollo`.`doadores` (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`colaboradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `funcao` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`contas_pagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`contas_pagas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NOT NULL,
  `data_pagamento` VARCHAR(100) NOT NULL,
  `valor` FLOAT NOT NULL,
  `observacao` TEXT(999) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`historico_contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`historico_contas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
  )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `apollo`.`historico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT,
  `data` VARCHAR(100),
  `tipo` VARCHAR(100),
  `categoria` VARCHAR(100),

  `valorDoacao` FLOAT,
  `nomeDoador` VARCHAR(255) NULL,
  `dataDoacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
    UNIQUE INDEX `nomeDoador_UNIQUE` (`nomeDoador` ASC) VISIBLE
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `apollo`.`historico_doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apollo`.`historico_doacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `data` VARCHAR(255) NULL,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`nome`) REFERENCES doadores(nome) ON UPDATE CASCADE
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
